Repository swrlab/ard-eventhub, pull requests merged in 2021-03, with the labels that each got.

#26 Dev/ard core api
  README.md
  openapi.json
  openapi.yaml
  package.json
  src/data/coreApi.json
  src/ingest/auth/middleware/verify.js
  src/ingest/events/post.js
  src/ingest/index.js
  src/ingest/subscriptions/delete.js
  src/ingest/subscriptions/get.js
  src/ingest/subscriptions/list.js
  src/ingest/subscriptions/post.js
  src/ingest/topics/list.js
  src/utils/pubsub/_publisherClient.js
  src/utils/pubsub/createSubscription.js
  src/utils/pubsub/createTopic.js
  src/utils/pubsub/getSubscription.js
  src/utils/pubsub/getSubscriptions.js
  src/utils/pubsub/index.js
  src/utils/pubsub/mapSubscription.js
  src/utils/response/index.js
  src/utils/response/notFound.js
  test/ingest.test.js
  yarn.lock
Labels: enhancement

#32 Docs and Keys
  .eslintrc.json
  .github/workflows/ingest-pull.yml
  .github/workflows/ingest-push.yml
  .markdownlintignore
  .nojekyll
  CHANGELOG.md
  README.md
  config/index.js
  config/stageConfig.js
  config/swaggerUI.js
  docs/AUTHENTICATION.md
  docs/EVENTS.md
  docs/README.md
  docs/SECRETS.md
  docs/STAGES.md
  docs/TYPES.md
  docs/USERS.md
  docs/_SIDEBAR.md
  index.html
  license.sh
  openapi.json
  openapi.yaml
  package.json
  src/ingest/README.md
  src/ingest/auth/middleware/verify.js
  src/ingest/auth/reset/post.js
  src/ingest/events/post.js
  src/ingest/index.js
  src/ingest/router.js
  src/ingest/subscriptions/delete.js
  src/ingest/subscriptions/get.js
  src/ingest/subscriptions/list.js
  src/ingest/subscriptions/post.js
  src/utils/datastore/_client.js
  src/utils/datastore/delete.js
  src/utils/datastore/load.js
  src/utils/datastore/save.js
  src/utils/firebase/index.js
  src/utils/firebase/refreshToken.js
  src/utils/firebase/sendPasswordResetEmail.js
  src/utils/firebase/signInWithEmailAndPassword.js
  src/utils/firebase/verifyToken.js
  src/utils/getHostType.js
  src/utils/loggerDev.js
  src/utils/pubsub/_client.js
  src/utils/pubsub/_publisherClient.js
  src/utils/pubsub/_subscriberClient.js
  src/utils/pubsub/publishMessage.js
  src/utils/tracer/index.js
  test/README.md
  test/ingest.test.js
  yarn.lock
Labels: documentation, enhancement

#39 Hotfix contenttype and testing
  .eslintrc.json
  CHANGELOG.md
  README.md
  docs/STAGES.md
  openapi.json
  openapi.yaml
  package.json
  src/ingest/events/post.js
  src/ingest/router.js
  src/utils/pubsub/publishMessage.js
  src/utils/response/badRequest.js
  test/ingest.test.js
Labels: bug

#43 Dev/fix new eslint
  .eslintrc.json
  CHANGELOG.md
  README.md
  config/swaggerUI.js
  docs/OPENAPI.md
  docs/_SIDEBAR.md
  openapi.json
  openapi.yaml
  package.json
  src/ingest/auth/login/post.js
  src/ingest/auth/middleware/verify.js
  src/ingest/auth/refresh/post.js
  src/ingest/events/post.js
  src/ingest/subscriptions/delete.js
  src/ingest/subscriptions/get.js
  src/ingest/subscriptions/list.js
  src/ingest/subscriptions/post.js
  src/ingest/topics/list.js
  src/utils/datastore/delete.js
  src/utils/datastore/index.js
  src/utils/datastore/load.js
  src/utils/datastore/save.js
  src/utils/firebase/signInWithEmailAndPassword.js
  src/utils/loggerDev.js
  src/utils/pubsub/createSubscription.js
  src/utils/pubsub/createTopic.js
  src/utils/pubsub/deleteSubscription.js
  src/utils/pubsub/getSubscription.js
  src/utils/pubsub/getSubscriptions.js
  src/utils/pubsub/getTopic.js
  src/utils/pubsub/getTopics.js
  src/utils/pubsub/index.js
  src/utils/pubsub/mapSubscription.js
  src/utils/response/index.js
  src/utils/response/internalServerError.js
  src/utils/response/notFound.js
  src/utils/response/ok.js
  src/utils/user/index.js
  test/example.test.js
  test/ingest.test.js
Labels: feature

#44 Staging fixes
  .github/workflows/ingest-push.yml
  CHANGELOG.md
  Dockerfile.ingest
  README.md
  docs/NAMING.md
  docs/QUICKSTART.md
  docs/STAGES.md
  docs/USERS.md
  docs/_SIDEBAR.md
  openapi.json
  openapi.yaml
  package.json
  src/ingest/auth/middleware/verify.js
  src/ingest/router.js
  src/ingest/subscriptions/delete.js
  src/ingest/subscriptions/get.js
  src/ingest/subscriptions/post.js
  src/ingest/topics/list.js
  src/utils/pubsub/createSubscription.js
  src/utils/pubsub/createTopic.js
  src/utils/pubsub/getTopics.js
Labels: bug, documentation, feature

#45 set optional fields `nullable` and remove `isInternal` from POST /events
  CHANGELOG.md
  openapi.json
  openapi.yaml
  package.json
Labels: bug

#47 Dev/unit tests update
  .eslintrc.json
  CHANGELOG.md
  README.md
  openapi.json
  openapi.yaml
  package.json
  test/README.md
  test/example.test.js
  test/ingest.test.js
  yarn.lock
Labels: feature

#53 [#50] Core-ID migration
  .gitignore
  CHANGELOG.md
  Dockerfile.ingest
  README.md
  config/coreIdPrefixes.json
  config/index.js
  docs/NAMING.md
  docs/QUICKSTART.md
  docs/STAGES.md
  docs/USERS.md
  openapi.json
  openapi.yaml
  package.json
  src/ingest/auth/middleware/verify.js
  src/ingest/events/post.js
  src/ingest/index.js
  src/ingest/subscriptions/delete.js
  src/ingest/subscriptions/get.js
  src/ingest/subscriptions/list.js
  src/ingest/subscriptions/post.js
  src/ingest/topics/list.js
  src/utils/core/createHashedId.js
  src/utils/core/getPublisher.js
  src/utils/core/index.js
  src/utils/datastore/save.js
  src/utils/logger/index.js
  src/utils/loggerDev.js
  src/utils/pubsub/buildId.js
  src/utils/pubsub/convertId.js
  src/utils/pubsub/createSubscription.js
  src/utils/pubsub/createTopic.js
  src/utils/pubsub/getSubscription.js
  src/utils/pubsub/getSubscriptions.js
  src/utils/pubsub/getTopic.js
  src/utils/pubsub/getTopics.js
  src/utils/pubsub/index.js
  src/utils/pubsub/mapSubscription.js
  src/utils/pubsub/publishMessage.js
  src/utils/tracer/index.js
  test/ingest.test.js
  yarn.lock
Labels: bug, feature
