Repository swrlab/ard-eventhub, pull requests merged in 2021-06, with the labels that each got.

#95 Feature/dts plugin
  .env.example
  .github/workflows/ingest-pull.yml
  .github/workflows/ingest-push.yml
  CHANGELOG.md
  Dockerfile.ingest
  README.md
  config/index.js
  docs/QUICKSTART.md
  openapi.json
  openapi.yaml
  package.json
  src/coreId/index.js
  src/ingest/README.md
  src/ingest/events/post.js
  src/ingest/pubsub/index.js
  src/ingest/pubsub/verify.js
  src/ingest/router.js
  src/utils/plugins/dts/event.js
  src/utils/plugins/dts/index.js
  src/utils/plugins/index.js
  src/utils/secrets/_client.js
  src/utils/secrets/get.js
  src/utils/secrets/index.js
  yarn.lock
Labels: feature

#103 Adding PR commenter
  .github/workflows/ingest-pull.yml
  .github/workflows/ingest-push.yml
Labels: feature

#104 pull request fixes for github actions
  .github/dependabot.yaml
  .github/workflows/ingest-pull.yml
  .github/workflows/ingest-push.yml
Labels: feature, safe to test

#105 reset yarn.lock to fix CVE-2021-32640
  .github/workflows/ingest-push.yml
  yarn.lock
Labels: safe to test, security

#124 remove body-parser (part of express since 4.16/17.0)
  README.md
  package.json
  src/ingest/router.js
Labels: dependencies

#125 Dev/dep updates
  CHANGELOG.md
  openapi.json
  openapi.yaml
  package.json
  yarn.lock
Labels: dependencies

#127 fix changelog dates and entries
  CHANGELOG.md
Labels: documentation, safe to test
