Repository swrlab/ard-eventhub, pull requests merged in 2021-05, with the labels that each got.

#72 Expose api spec in ingest
  config/swaggerUI.js
  src/ingest/router.js
Labels: feature

#82 update dependencies
  CHANGELOG.md
  openapi.json
  openapi.yaml
  package.json
  yarn.lock
Labels: dependencies

#73 Docs: Reorder types, add concrete examples
  docs/TYPES.md
Labels: documentation

#94 Dev/update 1.0.2
  CHANGELOG.md
  README.md
  docs/OPENAPI.md
  docs/TYPES.md
  openapi.json
  openapi.yaml
  package.json
Labels: documentation
